### ISSUE TITLE
linkerd inject should warn when an input config file is un-injectable

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd2#1516]
Per #1103, we should update `linkerd inject` to emit warnings if the config file supplied to it cannot be injected. Some of the reasons why the config can't be injected are as follows:

- [x] #1603 It's malformed
- [x] #1603 It uses Host networking
- [x] #1617 It uses UDP, not TCP
- [x] #1619 It contains init containers for other known sidecars
  - linkerd
  - istio
  - contour
- [x] #1603 It doesn't contain any injectable resources
