### ISSUE TITLE
MaterialUI followup: Navigation/Sidebar

### ISSUE THREAD

**Issue by rmars** [linkerd/linkerd2#1781]
The dashboard was converted to material-ui in #1776.

Things to be done:
- [x] #1810 I removed the list of resources per namespace and the namespace dropdown in the sidebar added in #1500 for simplicity. we should re-add it. I restructured the Navigation to be part of a larger component which renders the page as a subcomponent, which should make future work on #1669 easier
- [x] #1827 Side navigation doesn’t go all the way down on the Overview page
- [x] #1830 The icons for the side navigation were chosen without a lot of thought. Revisit this, as done in #1637. Resources that can help: https://material.io/tools/icons/?icon=home&style=baseline, https://materialdesignicons.com/. You can also use FontAwesome: (https://material-ui.com/style/icons/#font-icons)
