### ISSUE TITLE
Focus install by role and stage

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#2337]
### Task Breakdown

- [x] #2719 introduce 2 new subcommands: `admin` and `user`
- [x] #2719 finalize stage naming
- [x] #2719 templatize stages
- [x] #2723 corresponding `linkerd upgrade` updates
- [x] #2765 corresponding `linkerd check` updates
- [x] #2474 `--single-namespace` removal
- [x] #2719 unit tests for subcommands
- [x] #2723 integration tests for subcommands

### Tasks we may or may not do

- [ ] disable `linkerd install`
- [ ] `install-sp` integration
- [ ] `install-cni` integration

---

# Previous

### What problem are you trying to solve?

Today, Linkerd has a all-in-one install via `linkerd install`. As features have been added, this is becoming to be a larger problem because:

- CRDs and their resource definitions cannot be applied at the same time. This has created a new `install-sp` command that users need to run after `install` if they would like service profiles for the control plane. While control plane service profiles are optional right now, it is likely that they will be required in the future to support new functionality.
- Teams run on locked down clusters where there are two different individuals. One is a cluster admin that can add things such as CRDs and ClusterRoles and one is a namespace admin that can add Roles and Deployments. There is a hypothesis that cluster admins do not want to operate the components of Linkerd, simply audit that namespace admins won't hurt the cluster.
- The CNI plugin introduces a step where it must be installed before the control plane components themselves.

### How should the problem be solved?

To address these issues, the install should be separated into multiple phases. By using `install` subcommands to implement these phases, `linkerd check --pre` can be integrated into the install experience. As a tldr:

```bash
$ linkerd install config | kubectl apply -f -
$ linkerd install components | kubectl apply -f -
```

#### Pre-install experience

- Move `check --pre` into the existing `install` command.
- Order `linkerd-version` checks first instead of last.

For users without `cluster-admin`:

```bash
$ linkerd install
linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version

pre-kubernetes-cluster-setup
----------------------------
√ control plane namespace does not already exist
× can create Namespaces
× can create ClusterRoles
× can create ClusterRoleBindings
× can create CustomResourceDefinitions

pre-kubernetes-setup
--------------------
√ can create ServiceAccounts
√ can create Services
√ can create Deployments
√ can create ConfigMaps
√ can use NET_ADMIN

Status check results are ×

It appears that the current user does not have the required permissions. Take a
look at https://linkerd.io/2/install/#permissions for some details on what's
required and ways around it.
```

This doc would explain what permissions are required, suggest running `linkerd install config` and recommend passing the YAML to a `cluster-admin`.

Users that do have the correct privileges but run on a cluster with restrictive PSP:

```bash
$ linkerd install
linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version

pre-kubernetes-cluster-setup
----------------------------
√ control plane namespace does not already exist
√ can create Namespaces
√ can create ClusterRoles
√ can create ClusterRoleBindings
√ can create CustomResourceDefinitions

pre-kubernetes-setup
--------------------
√ can create ServiceAccounts
√ can create Services
√ can create Deployments
√ can create ConfigMaps
× can use NET_ADMIN

Status check results are ×

The current cluster has a restrictive PodSecurityPolicy that does not allow
pods to use NET_ADMIN. Take a look at https://linkerd.io/2/install/#psp.
```

The doc in question would then recommend users continue with the install but run `linkerd install forwarding` alongside `config` and `components` with the requisite flags.

```bash
$ linkerd install
linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version

pre-kubernetes-cluster-setup
----------------------------
√ control plane namespace does not already exist
√ can create Namespaces
√ can create ClusterRoles
√ can create ClusterRoleBindings
√ can create CustomResourceDefinitions

pre-kubernetes-setup
--------------------
√ can create ServiceAccounts
√ can create Services
√ can create Deployments
√ can create ConfigMaps

Status check results are √

To install Linkerd on your cluster, run:

  linkerd install config | kubectl apply -f -
  linkerd check config
  linkerd install components | kubectl apply -f -
  linkerd check
```

On any cluster that is completely open, a user will be able to cut/paste the commands and get a very similar one shot experience that exists today.

#### Cluster Config

The first step would contain all the resources that require `cluster-admin`. This primarily becomes RBAC that can be handed off to a `cluster-admin` or audited. I'm proposing a couple other changes:

- Inject becomes a default install (or at least the roles and bindings).

```bash
$ linkerd install config | kubectl apply -f -
namespace/linkerd created
serviceaccount/linkerd-ca created
serviceaccount/linkerd-controller created
serviceaccount/linkerd-grafana created
serviceaccount/linkerd-prometheus created
serviceaccount/linkerd-proxy-injector created
serviceaccount/linkerd-web created
clusterrole.rbac.authorization.k8s.io/linkerd-linkerd-ca created
clusterrole.rbac.authorization.k8s.io/linkerd-linkerd-controller created
clusterrole.rbac.authorization.k8s.io/linkerd-linkerd-prometheus created
clusterrole.rbac.authorization.k8s.io/linkerd-linkerd-proxy-injector created
clusterrolebinding.rbac.authorization.k8s.io/linkerd-linkerd-ca created
clusterrolebinding.rbac.authorization.k8s.io/linkerd-linkerd-controller created
clusterrolebinding.rbac.authorization.k8s.io/linkerd-linkerd-prometheus created
clusterrolebinding.rbac.authorization.k8s.io/linkerd-linkerd-proxy-injector created
customresourcedefinition.apiextensions.k8s.io/serviceprofiles.linkerd.io created
```

There needs to be a way to verify that someone has run `linkerd install config` on a cluster. This makes sure everything setup correctly and handles the potential issue of a asynchronous addition (emailing the YAML for example).

For a failure case:

```bash
$ linkerd check config
√ has linkerd Namespace
× has all ServiceAccounts
√ has all ClusterRoles
√ has all ClusterRoleBindings
√ has CRD

Check results are ×

Missing serviceaccount/linkerd-web, run linkerd config to fix.
```

For success:

```bash
$ linkerd check config
√ has linkerd Namespace
√ has all ServiceAccounts
√ has all ClusterRoles
√ has all ClusterRoleBindings
√ has CRD
```

Note: this check doesn't feel right, the command and the output are both odd and don't match other commands. Any good suggestions?

#### Forwarding

Install the CNI plugin in preparation of components.

```bash
$ linkerd install forwarding --dest-cni-bin-dir /home/kubernetes | kubectl apply -f -
namespace/linkerd configured
serviceaccount/linkerd-cni created
clusterrole.rbac.authorization.k8s.io/linkerd-cni created
clusterrolebinding.rbac.authorization.k8s.io/linkerd-cni created
configmap/linkerd-cni-config created
daemonset.extensions/linkerd-cni created
```

Then check:

```bash
$ linkerd check forwarding
√ cluster config is compatible
√ is running the DaemonSet
√ has configured CNI on every node in the cluster
√ pods are correctly having traffic forwarded
```

#### Components

This command can be run by namespace admins and allows them to manage the components themselves.

- `--single-namespace` gets folded into this command. The primary difference currently is between ClusterRoles and Roles. The biggest question is whether CRDs will become required by the control plane in the future.
- The namespace is only in `config` and not `components`.

```bash
$ linkerd install components | kubectl apply -f -
serviceaccount/linkerd-ca unchanged
serviceaccount/linkerd-controller unchanged
serviceaccount/linkerd-grafana unchanged
serviceaccount/linkerd-prometheus unchanged
serviceaccount/linkerd-proxy-injector unchanged
serviceaccount/linkerd-web unchanged
role.rbac.authorization.k8s.io/linkerd-linkerd-ca created
role.rbac.authorization.k8s.io/linkerd-linkerd-controller created
role.rbac.authorization.k8s.io/linkerd-linkerd-prometheus created
role.rbac.authorization.k8s.io/linkerd-linkerd-proxy-injector created
rolebinding.rbac.authorization.k8s.io/linkerd-linkerd-ca created
rolebinding.rbac.authorization.k8s.io/linkerd-linkerd-controller created
rolebinding.rbac.authorization.k8s.io/linkerd-linkerd-prometheus created
rolebinding.rbac.authorization.k8s.io/linkerd-linkerd-proxy-injector created
service/linkerd-controller-api created
service/linkerd-grafana created
service/linkerd-prometheus created
service/linkerd-proxy-api created
service/linkerd-proxy-injector created
service/linkerd-web created
deployment.extensions/linkerd-ca created
deployment.extensions/linkerd-controller created
deployment.extensions/linkerd-grafana created
deployment.extensions/linkerd-prometheus created
deployment.apps/linkerd-proxy-injector created
deployment.extensions/linkerd-web created
configmap/linkerd-grafana-config created
configmap/linkerd-prometheus-config created
configmap/linkerd-proxy-injector-sidecar-config created
```

With a final check for good luck:

```bash
$ linkerd check
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version

linkerd-existence
-----------------
√ control plane namespace exists
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-api
-----------
√ control plane pods are ready
√ can query the control plane API
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus

linkerd-service-profile
-----------------------
√ no invalid service profiles

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √
```

#### Helm Chart

The helm chart should be separated into similar sections so that it could be installed at once or in each of these pieces. The `crd-install` hook must be used, otherwise it should map 1:1 with the proposed install flow.

### Any alternatives you've considered?

See #2164 for a lot of discussion and alternatives.

### Open Questions

- What is the impact on `--linkerd-namespace` for each step? The role bindings in `config` will need to be namespace specific and it would be nice to allow users to operate multiple versions of Linkerd in different namespaces (impacting the roles as well).
- `linkerd check config` doesn't feel quite right. It would be weird to have a `linkerd install` run fail on half the things and still be okay though. Maybe the failures become warnings if config/cni is running correctly?
- How should the roles and components be separated for `linkerd install forwarding`. The same person would be doing it and there are no ordering requirements.
- The separation between `config` and `components` theoretically suggests that namespace owners can upgrade without running both commands. Is that a use case that should be encouraged?

**Comment by klingerf** [comment]
Just curious, how does this issue relate to #2164?

**Comment by grampelberg** [comment]
@klingerf I'm trying to organize everything from #2164 and think through the details a little bit more. Halfway through writing this up =)

**Comment by klingerf** [comment]
Ok cool, works for me.

**Comment by grampelberg** [comment]
Okay, I think I've got the entire flow laid out @klingerf and @siggy. See what you think!

**Comment by siggy** [comment]
Thanks for the writeup @grampelberg. Some thoughts:

I'm onboard with:
- Subcommands, to elevate the stages above flags
- Rolling `--single-namespace` into the namespace admin command
- Eliminating `install-sp`

Open questions:
- Is it possible to keep `install-cni` out of scope for this change, as it won't necessarily be a recommended install flow, at least initially? We could always roll it into `linkerd install` at a later point.
- Re: `config` / `components` nomenclature, I think that aligns well with what's actually being installed, but does not convey ordering or privilege. Ideally we'd use terms that convey all 3 of those concepts. I think `admin` / `user` conveys at least 2.
- I think we can leverage a bare `linkerd install` command to inform (existing and new) users on how to proceed:
    ```bash
    $ linkerd install
    Error: accepts 1 arg(s), received 0
    Usage:
      linkerd install (admin|user) [flags]

    Examples:
      # Default install.
      linkerd install admin | kubectl apply -f -
      linkerd install user | kubectl apply -f -

      # Install Linkerd into a non-default namespace.
      linkerd install admin -l linkerdtest | kubectl apply -f -
      linkerd install user -l linkerdtest | kubectl apply -f -

      # Install Linkerd with only namespace-wide privileges
      linkerd install user --single-namespace -l myapp | kubectl apply -f -

    Flags:
    ...
    ```
- Related to the previous point, I think confining all `install`-related commands to outputting install configs, and `check`-related commands to performing checks will be clearer to the user. Check/install flow could go something like:
    ```bash
    # check all levels of privilege, inform the user if they are capable of installing as admin+user, just user, or neither
    linkerd check --pre

    linkerd install admin | kubectl apply -f -
    linkerd check admin

    linkerd install user | kubectl apply -f -
    linkerd check user

    # check for complete installation
    linkerd check
    ```
- Per requirement 3 in https://github.com/linkerd/linkerd2/issues/2164#issuecomment-458265137, we need to support installation if a user has only namespace admin privileges. Does this mean the user would do:
    ```bash
    linkerd install admin --single-namespace
    linkerd install user [--single-namespace?]
    ```
    or:
    ```bash
    linkerd install user [--single-namespace?]
    ```
    I think the latter is doable.

**Comment by adleong** [comment]
The ClusterRoleBindings generated by `linkerd install config` will restrict which namespaces the Linkerd control plane can be installed into and which namespaces those control planes can watch.

Ideally we should be able to support multiple namespace isolated control planes in a single cluster, while also having sane and simple defaults that work for most people.  I have a proposal in https://github.com/linkerd/linkerd2/issues/2164#issuecomment-459055439 which describes how to do this with the `--data-plane-namespaces` and `--control-plane-namespaces` flags.

I'm about 60% certain that we don't need any kind of `--single-namespace` flag and can simply rely on RBAC and have the Linkerd control plane only watch namespaces that it has RBAC permissions to watch.

**Comment by grampelberg** [comment]
@adleong I'm not sure I understand why you need `--data-plane-namespaces`?

**Comment by grampelberg** [comment]
> * Is it possible to keep `install-cni` out of scope for this change

I tried to think through the end state, `install-cni` should definitely not be tackled all at once with the majority of these changes.

> * Re: `config` / `components` nomenclature, I think that aligns well with what's actually being installed, but does not convey ordering or privilege. Ideally we'd use terms that convey all 3 of those concepts. I think `admin` / `user` conveys at least 2.

I'm not a huge fan of the roles, `linkerd install admin` and `linkerd install user` just seems weird - I'm not installing an admin or a user. Your ordering point is something I'd not thought of and is a great point though. Maybe `linkerd install step-one` and `linkerd install step-two`? If I had to rank the three I'd say:

1. Ordering
1. What's happening to the cluster
1. Privilege

> * I think we can leverage a bare `linkerd install` command to inform (existing and new) users on how to proceed

+1, I do think we should be using something check-like to recommend the method they should use based off the current state of the cluster though.

> * Related to the previous point, I think confining all `install`-related commands to outputting install configs, and `check`-related commands to performing checks will be clearer to the user.

Works for me, I primarily want to get rid of `--pre`, especially as it doesn't fit the new setup very well. Maybe `linkerd check cluster`?

> * Per requirement 3 in [#2164 (comment)](https://github.com/linkerd/linkerd2/issues/2164#issuecomment-458265137), we need to support installation if a user has only namespace admin privileges.

Based off yesterday's conversations I don't think `--single-namespace` makes any sense. That said, it should be possible to just `linkerd install user` in this world as that outputs the Roles and RoleBindings required to work.

**Comment by adleong** [comment]
`--data-plane-namespaces` specify the namespaces which can be watched by the ClusterRole.  Without such a flag, we'd need the linkerd-controller ClusterRole to be able to watch all namespaces.  I think this is how it works today, but is probably over-permissive in some cases.

Probably not critical, but it's an easy thing to include that feels right for completeness and fits the theme of permissions lockdown.

**Comment by grampelberg** [comment]
> `--data-plane-namespaces` specify the namespaces which can be watched by the ClusterRole

ClusterRoles encompass all namespaces. We'd need to get rid of the ClusterRoles and do a Role for every namespace (as RBAC is additive in k8s).

**Comment by adleong** [comment]
Ah, you're right, I got mixed up about how that worked.  Seems a bit weird that you can't have a cluster level ClusterRole which grants access to a subset of namespaces... but anyway!  

Given that, yeah, `--data-plane-namespaces` doesn't make sense.

**Comment by siggy** [comment]
Notes on ordering/dependency of components:

- a deployment referencing an unknown ConfigMap will successfully create a ReplicaSet and Pods, and eventually start, once that ConfigMap becomes available:

```bash
$ kubectl -n linkerd describe pod/linkerd-identity-5db4f95f6-lgm6d
...
Events:
  Type     Reason                 Age              From                         Message
  ----     ------                 ----             ----                         -------
  Normal   Scheduled              2m               default-scheduler            Successfully assigned linkerd-identity-5db4f95f6-lgm6d to docker-for-desktop
  Normal   SuccessfulMountVolume  2m               kubelet, docker-for-desktop  MountVolume.SetUp succeeded for volume "linkerd-identity-end-entity"
  Normal   SuccessfulMountVolume  2m               kubelet, docker-for-desktop  MountVolume.SetUp succeeded for volume "linkerd-identity-token-5v8gt"
  Normal   SuccessfulMountVolume  2m               kubelet, docker-for-desktop  MountVolume.SetUp succeeded for volume "identity-issuer"
  Warning  FailedMount            1m (x8 over 2m)  kubelet, docker-for-desktop  MountVolume.SetUp failed for volume "config" : configmaps "linkerd-config-foo" not found
  Warning  FailedMount            22s              kubelet, docker-for-desktop  Unable to mount volumes for pod "linkerd-identity-5db4f95f6-lgm6d_linkerd(13d30db6-6213-11e9-a507-025000000001)": timeout expired waiting for volumes to attach or mount for pod "linkerd"/"linkerd-identity-5db4f95f6-lgm6d". list of unmounted volumes=[config]. list of unattached volumes=[config identity-issuer linkerd-identity-end-entity linkerd-identity-token-5v8gt]
  Normal   SuccessfulMountVolume  16s              kubelet, docker-for-desktop  MountVolume.SetUp succeeded for volume "config"
  Normal   Started                8s               kubelet, docker-for-desktop  Started container
```

- a deployment referencing an unknown ServiceAccount will successfully create a ReplicaSet, and eventually create pods, once that ServiceAccount becomes available:
```bash
$ kubectl -n linkerd describe replicaset.apps/linkerd-identity-78b759944
...
Events:
  Type     Reason            Age               From                   Message
  ----     ------            ----              ----                   -------
  Warning  FailedCreate      2m (x16 over 5m)  replicaset-controller  Error creating: pods "linkerd-identity-78b759944-" is forbidden: error looking up service account linkerd/linkerd-identity-sa: serviceaccount "linkerd-identity-sa" not found
  Normal   SuccessfulCreate  11s               replicaset-controller  Created pod: linkerd-identity-78b759944-mbn72
```

**Comment by alpeb** [comment]
@siggy So it seems to me there are only two possible ordering/dependency issues that can occur:

1. ConfigMap updates that aren't caught by services that don't hot-reload them (#2671). That's identity changes for the Destination and Identity services, and UUID changes for Web. Given those are rare changes I wonder if it's worth for them to watch for ConfigMap changes.
2. CRD and `install-sp`. Even if done in separate stages, we gotta double-check if the CRD is available fast enough (e.g. unlike ConfigMaps updates which can take a while)

**Comment by siggy** [comment]
#2765 makes this feature complete, closing. will follow up with subsequent work in other tickets.
