### ISSUE TITLE
Linkerd 2.3 release test plan

### ISSUE THREAD

**Issue by admc** [linkerd/linkerd2#2459]
We have testing to do in order to feel confident about a 2.3 release.

- Manual testing
  - [x] #2516 Mutli-cloud (AKS, EKS, GKE, DO)
    - Manual script to validate identity and auto inject
    - Run integration tests
  - [x] #2518 Introduce test plan for service profiles
    - [x] #2638 introduce integration tests
    - [x] #2685 service profile metrics
  - [x] #2517 Emojivoto / books 
    - identity (TLS)
    - more than 100 replicas
    - vote-bot/traffic at 1k rps
    - Run with more than 100 services, all with service profiles (copy emoijvoto)
      - increase replicas
      - increase namespaces
  - [x] #2578 Use the [lifecycle](https://github.com/linkerd/linkerd-examples/tree/0eeb9d34ce3e59d18291fc1ac9831e8ce2284c4d/lifecycle) environment to test service discovery and caching
- Soak for a week
  - solicit the community for edge release input, via tweets/slack
- Automated testing
  - [x] Identity (current tests w/ TLS)
    - [x] Once part of default install, integration tests will do some validation automatically
    - [x] #2519 Modify existing TLS integration tests to perform additional validation, via metrics, etc
    - [x] #2505 Proxy integration tests
    - [ ] `controller/identity` unit tests (https://github.com/linkerd/linkerd2/pull/2521#pullrequestreview-215958707)
  - [x] #2520 Add service profile integration tests
  - [ ] Injection integration tests
    - [x] #2595 with and without `--proxy-auto-inject`
    - [x] #2616 cli inject integration tests
    - [ ] cli inject with and without auto inject
    - [x] #2616 pod deploys and deployment deploys
    - [x] #2616 `linkerd.io/inject: enabled`, `linkerd.io/inject: disabled`, and no annotation present
    - [x] #2616 pod annotations and deployment annotations
    - [ ] creating and updating
  - [x] `linkerd upgrade` (https://github.com/linkerd/linkerd2/pull/2564#discussion_r270567233)
    - [x] #2637 unit tests
      - [x] #2639 input/output unit tests
      - [x] #2672 individual function unit tests / refactor
    - [x] #2669 integration tests

Also this needs to be turned into a test plan doc / checklist that is checked into the repo so that we do this work before any stable releases.
