### ISSUE TITLE
Version usage reporting

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#2961]
### What problem are you trying to solve?

It is extremely valuable to know what versions of Linkerd are currently in use and the environments they're being used in. This helps prioritize testing, backports and gives a picture of what is important to users.

### How should the problem be solved?

As part of install, add a `CronJob` that issues a request to `versioncheck.linkerd.io` every 24 hours with the following query params:

#### P0

- [x] #3056 Linkerd version
- [x] #3056 Cluster UUID
- [x] #3056 Kubernetes version
- [x] #3056 Installation time

#### P1

- [x] #3238 CPU/Memory for prometheus and destination
  - max mem over all available time
  - p95 cpu over all available time
- [x] #3238 CPU/Memory for the data plane proxies

#### P2

- [ ] Memory histogram of the data plane proxies
- [ ] Histogram of latency introduced by the proxy

#### P3

- [x] #3059 Number of injections
- [ ] CPU/memory usage of each container in the control plane
- [ ] Histogram of cpu usage of the data plane proxies
- [ ] Histogram of RPS by proxy

**Comment by grampelberg** [comment]
After having a couple conversations about performance today, I’d love to see some extra data added to this so that it’ll be easier to do sizing and prioritization of performance work. I added some extra values to the issue and put in some rough signaling to show how much I’d like it.

**Comment by siggy** [comment]
note for `Kubernetes environment (eg. GKE, AKS, EKS, …)`, we'll capture some of this implicitly as part of #3056 via k8s version. (for example GKE runs k8s version `v1.12.8-gke.10`).
