### ISSUE TITLE
Grafana Integration tracking ticket

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd2#420]
## Summary

With Prometheus already a first-class component of Conduit, Grafana is a natural extension of that deployment, enabling visualization of Conduit telemetry data. This ticket documents tasks to achieve preliminary Grafana integration for the next Conduit release.

Context: https://docs.google.com/document/d/12Cfzc6ghuxs93xXl1QSvUxFjU4mwJLaNcxBykvgF7Fg

Prototype: https://github.com/runconduit/conduit/pull/101

## Tasks
- [x] #423 Isolate templated config files from Go code
  - The [conduit install template](https://github.com/runconduit/conduit/blob/8bc7c5acde925c6124aafc2d56f13ae5904b5cf3/cli/cmd/install.go#L17) is hard-coded in `install.go`. Move this template into its own file to better accommodate a size and complexity increase, namely for adding Grafana dashboard files.
- [x] #444 Modify `conduit install` to include a Grafana container, configured to connect to Prometheus, with a sample dashboard.
- [x] add `Conduit Viz` and `Conduit Deployment`: for users' services
    - #500 templated view per-deployment, per time-window, approximates Conduit dashboard's deployment page in structure and data
- [x] #582 Grafana container in CrashLoopBackoff on GKE
- [x] #591 add `Conduit Health`: for the Conduit mesh itself
- [x] #637 Update Grafana dashboards to use new proxy metrics (depends on #429)
- [x] #590 Enable user access to the Grafana dashboard (note: https://github.com/runconduit/conduit/pull/444#discussion_r171115514), via at least one of:
  - A modified `conduit dashboard` command.
  - A new `conduit grafana` command.
  - Documenting a `kubectl port-forward` command.
- [x] #567 Modify templating of Grafana dashboards to accommodate very large JSON files
  - Format dashboard files for easier copy/paste 
- [x] #657 Modify templating of Grafana dashboards to support Conduit deployed in non-conduit namespaces
  - `label_values(requests_total{target_deployment!~\"conduit/.*\"}, target_deployment)`
  - utilize `conduit_io_control_plane_component="web"` / `conduit_io_control_plane_ns="conduit"`
  - one approach: https://github.com/runconduit/conduit/pull/444#discussion_r170398461
- [x] #678 Integrate Conduit and Grafana dashboards via linking and templating per-deployment
(https://github.com/runconduit/conduit/pull/444#discussion_r171358830)
- [x] #704 Handle deployments of the same name from different namespaces
- [x] #766 Standardize and polish Grafana for 0.4.0 release
- [x] #705 top-line and deployment dashboard template variables should fail gracefully when no deployments found (but other resources exist).
- [x] #904 Non-Conduit cluster health dashboards
- [ ] #706 handle non-deployment objects (namespaces, RCs, etc)
- [ ] #709 Enable time window switching in Conduit dashboard (integrate with Grafana?)

**Comment by siggy** [comment]
Only remaining tasks are #706 and #709. Closing this tracking ticket.
