### ISSUE TITLE
Prometheus add-on parent issue

### ISSUE THREAD

**Issue by Pothulapati** [linkerd/linkerd2#4375]
This is a parent issue of all the changes that will be done to make prometheus as an add-on. 

- [x] Move prometheus into a sub-chart and as a add-on
- [x] Relax or remove existing component dependencies on prometheus and for checks.
- [x] Add add-on specific checks, that see if the prometheus components are running correctly.
- [x] Add `global.prometheusUrl` for BYOP case., along with validation in helm
- [x] Add [check tooling](https://github.com/Pothulapati/rfc/blob/prom/design/0003-byop.md#linkerd-cli-tooling) for the BYOP case.
- [x] Bring your own prometheus linkerd website task
- [ ] Test Plan

**Comment by kleimkuhler** [comment]
@Pothulapati Correct me if I'm wrong but this can be closed now? The final thing would be the test plan (tracked in #5041) and that currently passes. That issue is only remaining open until I have retested with the RC.

**Comment by Pothulapati** [comment]
@kleimkuhler Yep, you are right. Only the testing with RC is left.
