### ISSUE TITLE
Parent issue for Simplifying State Management

### ISSUE THREAD

**Issue by Pothulapati** [linkerd/linkerd2#4914]
This is a parent issue to track the current work happening on Simplifying State Management as per https://github.com/linkerd/rfc/pull/35

---
- [ ]  Add a new linkerd-config-overrides secret
- [ ] Update the control-plane components to be able to get most configuration through
flags, and remove the dependency on the current linkerd cm.
- [ ] Remove the generation of `linkerd-config` cm.
- [ ] Update the upgrade flow to use the secrets, and give it priority over the
current `linkerd-config`.
- [ ] Update the check workflow to understand the current cluster state from the
new format.
- [ ] Update Add-ons individually to have its own configuration resource, and
update CLI for upgrades and checks accordingly.
