### ISSUE TITLE
Test plan for stable-2.9.1

### ISSUE THREAD

**Issue by alpeb** [linkerd/linkerd2#5315]
## Test Instructions

The stable-2.9.1 PR is at #5302. Please check the release notes and the commits tab for the list of cherry-picks from `main`.

For convenience, I've pushed the images  to my docker repo at https://github.com/alpeb?tab=packages
You can pull everything with:
```bash
$ DOCKER_REGISTRY=ghcr.io/alpeb bin/docker-pull stable-2.9.1
```
Then pull the CLI binaries with
```bash
$ DOCKER_REGISTRY=ghcr.io/alpeb bin/docker-pull-binaries stable-2.9.1
```
If you're on Mac, you should be able to use this:
```bash
$ target/release/linkerd2-cli-stable-2.9.1-darwin version
Client version: stable-2.9.1
Server version: unavailable
```

The `--registry` flag doesn't currently apply to addons, so you need to create this config file for Grafana:
```bash
$ cat linkerd-overrides.yml 
grafana:
  enabled: true
  image:
    name: ghcr.io/alpeb/grafana
```

Now you can run install with:
```bash
$ target/release/linkerd2-cli-stable-2.9.1-darwin install --registry ghcr.io/alpeb --config linkerd-overrides.yml
```

## Tests

- Upgrades:
  - [x] Upgrade from stable-2.8.1, with an injected app
    - [x] First upgrade only the control plane and verify the app with the old proxies remains sane
  - [x] Upgrade from stable-2.9.0

- Proxy changes:
  - [x] Run the benchmarks with H2 upgrades disabled, and verify we don't get OOM again
  - [x] Check the proxy client is no longer stuck talking to stale address after headless service rollout (#5209)
  - [x] Delete+recreate services/endpoints/profiles/trafficsplits and check service discovery is responding appropriately
  - [x] If possible, attempt reproducing the high-concurrency scenario that #5279 addressed

- CLI changes:
   - [x] Check `--linkerd-namespace` got fixed (#5239)
   - [x] Check `linkerd check` no longer complains about missing SAN in non-leaf certs (#5228)

**Comment by alpeb** [comment]
The benchmarks are no longer OOMing with H2 upgrades disabled :+1: (latency is bad with no H2 though :shrug: )
