### ISSUE TITLE
stable-2.11.3 release

### ISSUE THREAD

**Issue by kleimkuhler** [linkerd/linkerd2#8779]
@kleimkuhler 
- [x] #8430
- [x] #8143 This bug is not present on 2.11
- [x] #8719
- [x] #8010
- [x] #8475
- [x] #8583
- [x] #8590
- [x] #8734

Proxy cherry-picks should happen onto `v2.161.3`.

@hawkw 
- [x] #8666: linkerd/linkerd2-proxy#1758 cherry-pick
- [x] #8323: linkerd/linkerd2-proxy#1670 cherry-pick
- [x] #8539

Maybe
- [x] linkerd/linkerd2-proxy#1759 (@hawkw if the cherry-pick is straightforward)

---

- [ ] Release notes

**Comment by hawkw** [comment]
All the proxy backports (including the one for linkerd/linkerd2-proxy#1759) are up:
 - llinkerd/linkerd2-proxy#1801
 - linkerd/linkerd2-proxy#1802
 - linkerd/linkerd2-proxy#1803
 - linkerd/linkerd2-proxy#1804

**Comment by hawkw** [comment]
proxy bump: https://github.com/linkerd/linkerd2/pull/8789

**Comment by hawkw** [comment]
I believe this version has been released!
